services:
  teamcity-server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server-instance
    restart: always
    networks:
      backend:
        ipv4_address: 10.3.1.2
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    ports:
      - "8111:8111" 
  teamcity-agent:
    image: jetbrains/teamcity-agent
    container_name: teamcity-agent-instance
    restart: always
    networks:
      backend:
        ipv4_address: 10.3.1.3
    environment:
      SERVER_URL: http://10.3.1.2:8111
networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 10.3.1.0/24